# 	filter.R
#
# These functions use the results from the knn (i.e. the k most similar users) to
# to produce a list of recommended films, refined by genre if that is the desire
# of the user.
#


source("const.R")
source("query.R")


# This function takes the output from knn and then places all films that all the
# users thought were better than average in one large list, where the films
# are sorted by a score that I calculate, which is a function of of both the user's
# score for the film and my determined distance between the dataset user and the
# user of the recommender system.
combine_users_favorites <- function(k_list, user_data, test=FALSE) {
    if (test) {
        path <- ratings_test_path
    } else {
        path <- ratings_path
    }

    ratings_tbl <- read.csv(path, as.is=TRUE)
    average_score <- mean(ratings_tbl[["rating"]])

    cat("Selecting from similar user's favorites")
    full_film_recs <- list()

    # Build list of recommended films sorted by my scoring system
    # score = (users_score) * (user_distance)^(-1)
    for (i in 1:length(k_list)) {
        # Acquire info about current user's ID, distance, and film ratings
        current_user <- k_list[[i]][1]
        user_distance <- k_list[[i]][2]
        current_user_subset <- subset(ratings_tbl, subset=(userId == current_user))

        # Add film to full_film_recs if the user's score is above average
        for (j in 1:nrow(current_user_subset)) {
            users_score <- current_user_subset[["rating"]][j]
            cur_movieId <- current_user_subset[["movieId"]][j]

            # Don't recommend film if user has seen it already
            if(nrow(subset(user_data, subset=(V1 == cur_movieId))) == 1) {
                next
            }

            if (users_score > average_score) {
                score <- users_score * (user_distance**(-1))
                name <- movieId_to_str(cur_movieId)
                genre <- movieId_to_genre(cur_movieId)
                movieId <- cur_movieId

                datapoint <- c(score, name, genre, movieId)
                full_film_recs <- ordered_insert(full_film_recs, datapoint)
            }
        }

        # Progress bar
        cat(".")
    }
    
    # Newline after progress bar
    cat("\n")

    return(full_film_recs)
}


# This function inserts the vector called 'item' into the list called 'lst'.
# The first element of the 'item' vector is used to order the items in the list,
# and new items are inserted into their proper place relative to this order.
ordered_insert <- function(lst, item) {
    if (length(lst) == 0) {
        return(list(item))
    }

    # Insert in the middle of the list
    for (i in 1:length(lst)) {
        if (item[1] > lst[[i]][1]) {
            lst <- append(lst, list(item), i-1)

            return(lst)
        }
    }

    # Insert at the end of the list
    lst <- append(lst, list(item))
    return(lst)
}


# This function queries the user about filtering by genre. If the user wants to
# filter by gengre, then it looks at the list 'favorites' generated by
# combine_users_favorites(), picks out all the genres between those films, and
# asks users to choose between those genres. It then generates a new list from the
# old one entirely composed of films of that genre.
filter_by_genre <- function(favorites) {
    # Ask if user wants to filter by genre
    pmpt <- "Do you want to filter your results by genre? [y/n]\n"
    repeat {
        response <- readline(prompt = pmpt)

        if (response == "y") {
            break
        } else if (response == "n") {
            return(list(favorites, NA))
        }
    }

    # Produce list of genres
    genres <- c()

    for (i in 1:length(favorites)) {
        genre_str <- favorites[[i]][3]
        genre_list <- unlist(strsplit(genre_str, "[|]"))

        for (j in 1:length(genre_list)) {
            # If it's not in the genre list already
            if (!(genre_list[j] %in% genres)) {
                genres <- append(genres, genre_list[j])
            }
        }
    }

    genres <- sort(genres)
    genre_num <- length(genres)

    # Ask user to pick a genre
    cat(paste("\nPick a genre by selecting a number from 1 to ",genre_num,":\n",sep=""))
    for (i in 1:genre_num) {
        selector <- paste("[", i, "] ", sep="")

        if (genre_num > 9 && i < 10) {
            selector <- cat("", selector)
        }

        line <- paste(selector, genres[i], "\n", sep="")
        cat(line)
    }

    repeat {
        n <- readline()
        n <- as.integer(n)

        if (n < 0 || n > genre_num) {
            cat("Integer out of range. Try again.\n")
        } else {
            break
        }
    }

    genre_filter <- genres[n]

    # Filter out movies that don't have the genre in genre_filter
    recommendations <- list()
    for (i in 1:length(favorites)) {
        if (grepl(genre_filter, favorites[[i]][3])) {
            recommendations <- append(recommendations, list(favorites[[i]]))
        }
    }

    return(list(recommendations, genre_filter))
}
